CREATE TABLE BEJELENTES(BID INT PRIMARY KEY,Datum DATE,Diszpecser VARCHAR(50),Hivo varchar2(50),Telefonszam varchar2(50),Hely varchar2(50),Kikuldve NUMBER(1))

CREATE TABLE ORVOS(OID INT PRIMARY KEY,Nev VARCHAR2(50),FIZETES INT)

CREATE TABLE CSAPAT(CSID INT PRIMARY KEY,OID INT REFERENCES ORVOS(OID))

CREATE TABLE AUTO(AID INT PRIMARY KEY,Rendszam VARCHAR2(50))

CREATE TABLE KIVONULAS(KID INT PRIMARY KEY,Indulas TIMESTAMP,Erkezes TIMESTAMP,Leiras VARCHAR(100),CSID INT REFERENCES CSAPAT(CSID),AID INT REFERENCES AUTO(AID),BID INT REFERENCES BEJELENTES(BID))



